### ISSUE TITLE
[Device Virtual] Consume breaking changes in device-sdk-go dev.61

### ISSUE THREAD

**Issue by vli11** [edgexfoundry/device-virtual-go#371] opened 2023-03-27 21:35 UTC
# Tech Debt

### Affected Services [**REQUIRED**]
device-virtual-go can not be compiled successfully using device-sdk-go dev.61

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
~/source/repos/device-virtual-go$ make build
CGO_ENABLED=0 go build -tags "" -ldflags "-X github.com/edgexfoundry/device-virtual-go.Version=0.0.0" -trimpath -mod=readonly -o cmd/device-virtual ./cmd
# github.com/edgexfoundry/device-virtual-go/internal/driver
internal/driver/virtualdriver.go:86:86: cannot use dr.Properties.Minimum (variable of type *float64) as string value in argument to vd.read
internal/driver/virtualdriver.go:86:109: cannot use dr.Properties.Maximum (variable of type *float64) as string value in argument to vd.read
make: *** [Makefile:26: cmd/device-virtual] Error 1

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment] 2023-03-27 21:37
@vli11 , this is not a bug. It is part of our development cycle.

**Comment by cloudxxx8** [comment] 2023-03-28 01:42
Please just upgrade to dev.57 by closing it, and my team will follow up the upgrade development

**Comment by lenny-intel** [comment] 2023-03-28 14:34
@vli11 , looks like @cloudxxx8 wants his team to handle this. So we can put your PR on-hold until their fix is in.
@cloudxxx8 , @vli11 's PR is dependent on dev.60 which removes TOML package.

**Comment by cloudxxx8** [comment] 2023-03-28 14:36
@lenny-intel @vli11 I am fine with both team to do that.  Please do whatever you feel comfortable.

**Comment by vli11** [comment] 2023-03-28 17:09
@cloudxxx8 I will wait for your fix to continue toml to yaml conversion.

**Comment by weichou1229** [comment] 2023-03-30 10:41
> @cloudxxx8 I will wait for your fix on this issue to continue toml to yaml conversion.

@vli11 I opened the PR and use the YAML file you made from the previous commit for testing

**Closed** 2023-03-31 05:07 UTC
Labels: tech-debt
